version: "3.8"

services:
    zebrash-api:
        build: .
        ports:
            - "3009:3009"
        restart: unless-stopped
        environment:
            - PORT=3009
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3009/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
